### ISSUE TITLE
Latest download hangs

### ISSUE THREAD

**Issue by gganapat** [JerryI/wolfram-js-frontend#217]
**Describe the bug**
The start up hangs on start up at server: 2 after downloading latest version of wolfram-js-frontend.

**To Reproduce**

<img width="828" alt="Screenshot 2024-06-25 at 9 56 04 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/b1ba16d8-8d7b-49b3-bc2a-7a166fc3038e">

**Expected behavior**

clean start up

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser (Firefox)

**Comment by JerryI** [comment]
Have you tried to remove wl_*, .wl_* and wljs_*, .wljs_* in the project repo?

**Comment by gganapat** [comment]
Yes, I did what you suggested and removed all files and folders with the above prefixes. Still hanging.

**Comment by JerryI** [comment]
Hm... I am running the same one on my Air M1.
It might be occupied port issue. Could you please try

```bash
wolframscript -f Scripts/start.wls http 8080 ws 8081 ws2 8082 docs 8085
```

and a full log might also give additional hints

**Comment by gganapat** [comment]
Ok, I will do what you suggest. Also, this seems to work on my M1 Mac but not on my M2 Mac. I don;t think it has anything to do with the Mac model. Is is possibly linked to my M2 Mac being work computer and something is blocking now which was the case before? I guess we will know once I run the above on my M2.

thanks, gani -

**Comment by JerryI** [comment]
It might be somewhat related to permissions. But frankly speaking, I have never seen something like that on Mac. Odd...

**Comment by gganapat** [comment]
I did what you suggested - still hangs in the same place. Where would the log file be?
g-

**Comment by JerryI** [comment]
Only Electron wrapper can collect logs to a file. Here it must be printed directly to the terminal app you are using.

**Comment by gganapat** [comment]
How would I collect this info?

**Comment by JerryI** [comment]
> How would I collect this info?

In principle once you start it in the terminal it prints prints... and prints. I believe simple `Cmd+A` in the text field should do the job

**Comment by gganapat** [comment]
ok, here is the log file. Do what you can.

Thx!
[log.txt](https://github.com/user-attachments/files/15977976/log.txt)

**Comment by gganapat** [comment]
If this helps on my M1 Mac, the next message is:

 `>> LocalKernel >> local kernel link connected!
`

which implies that the local kernel link is not being connected in my M2 Mac - it hangs after the `server: 2 `message. Does that mean anything to you?

thx, gani -

**Comment by JerryI** [comment]
It looks like it hands on self test procedure. Autotest relies on `URLFetch`, which was reported to be buggy. 
I would suggest to fetch the changes I made #219 and #218 (no need in removing any folders), which allows to bypass autotest and get more information

```
wolframscript -f Scripts/start.wls http 8080 ws 8081 ws2 8082 docs 8085 bypasstest True
```

**Comment by gganapat** [comment]
Didn't work unfortunately. I cleared cache, downloaded latest version and ran above command. Page is blank and spinning on tab trying to load.

<img width="955" alt="Screenshot 2024-06-26 at 11 11 37 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/974a1d2b-068b-4240-a0d0-912272ef8eb0">

**Comment by JerryI** [comment]
Oh... The worst case scenario seems to be true. 😢  It is related to [CSockets](https://github.com/JerryI/CSocketListener/tree/dev2024) package, I believe. It is based on libuv and written in C.

We need to think about it together with @KirillBelovTest on how to debug this and provide some tools for you.

**Comment by JerryI** [comment]
Ok. If you like, you can help us to investigate this issue.
For this reason, there is a simple demo to check the area of it

clone this repository
```bash
git clone https://github.com/JerryI/wl-wlx
cd wl-wlx
```

and then try to run an example (just plain HTTP server + Sockets + template engine)

```bash
wolframscript -f Examples/Basic/Basic.wls
```

if it shows something on a page.

**Comment by gganapat** [comment]
Didn't work --

gani-

<img width="1243" alt="Screenshot 2024-06-28 at 3 33 15 PM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/72cf5f8e-b218-46c7-914f-e020ab46acc5">

**Comment by JerryI** [comment]
Sorry for that, I made a mistake. 
I pushed changes to WLX repo. Now it should work

**Comment by gganapat** [comment]
still the same as before - hangs.

<img width="520" alt="Screenshot 2024-06-28 at 6 02 39 PM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/69885672-8e54-4ab7-b760-9e2fae4e6e21">

**Comment by JerryI** [comment]
> still the same as before - hangs.

This is the same `Basic/Basic.wls` example (after fetching the recent commit i made to wlx repo), right?..

**Comment by gganapat** [comment]
No, it was the full one. I will try try the basic one.
g-

**Comment by gganapat** [comment]
still hangs.

<img width="769" alt="Screenshot 2024-06-29 at 9 07 17 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/4c08d280-722d-4acd-bc24-514a26675c27">

**Comment by JerryI** [comment]
Then, confirmed. It is a malfunctioning `sockets` interface. We will have a meeting soon with co-developers and discuss this issue.

**Comment by gganapat** [comment]
Ok, the latest version works! Thx! gani -

**Comment by JerryI** [comment]
> Ok, the latest version works! Thx! gani -

I still have no idea how it works, but we did not change anything related to sockets ;D
Anyway, I am super happy to hear that it works now for you
